<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>8804d8ee-8274-4d11-94b1-a20967da1dfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.Toggle-sc-cdwea1.guXPFl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3d6960ad-fbc4-483a-892c-4b5918536a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4bf8aaf8-570c-4cb8-a00b-14e7c1e025b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Toggle-sc-cdwea1 guXPFl</value>
      <webElementGuid>c1549f06-bb98-4783-b779-e2a6fc3d3c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ชาย</value>
      <webElementGuid>417545ed-65a6-49fd-9846-b0aac3c868d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/div[@class=&quot;content&quot;]/div[1]/div[@class=&quot;sc-1w7x3ft-0 haqBKz&quot;]/div[@class=&quot;sc-1ijt930-0 kpohkU&quot;]/form[1]/div[@class=&quot;BaseGap-sc-1wadqs8 dzKCbJ sc-1ijt930-1 bnMtCQ font-highlight rg16 sc-1ijt930-1 bnMtCQ font-highlight rg16&quot;]/div[@class=&quot;BaseGap-sc-1wadqs8 itjsHI&quot;]/div[@class=&quot;BaseGap-sc-1wadqs8 jbaUmy&quot;]/div[2]/div[@class=&quot;BaseGap-sc-1wadqs8 kugtby txabxh-0 dhaAIm txabxh-0 dhaAIm&quot;]/button[@class=&quot;Toggle-sc-cdwea1 guXPFl&quot;]</value>
      <webElementGuid>b2b704c4-d9ef-4f99-ac97-d688b069b005</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>46cb2c60-b6c4-4cb7-936b-8079b3d80cc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='body']/div[2]/div/div/div/form/div/div[2]/div[3]/div[2]/div/button</value>
      <webElementGuid>545c6d72-f46b-4a48-916e-b44a11cfd0e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='เพศ'])[1]/following::button[1]</value>
      <webElementGuid>8e582566-b31e-4f84-8458-591b7d61747a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ชื่อ'])[1]/following::button[1]</value>
      <webElementGuid>56cb5d7e-7927-4725-8174-a00c47a94257</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='หญิง'])[1]/preceding::button[1]</value>
      <webElementGuid>6c25b2ec-c1ea-4352-b4bc-c71588a0597e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/button</value>
      <webElementGuid>d702462a-6283-4055-bb5a-28c3591417c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'ชาย' or . = 'ชาย')]</value>
      <webElementGuid>e2b867df-e1b5-4367-8096-a1a7baffc8b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
