<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button__1</name>
   <tag></tag>
   <elementGuidId>fc494c3a-2f27-4c0a-a976-47a3dc34eb67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.StyledButton-sc-1lpnvbj.cryQQO.mt-36.mt-36</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bd5d4a2f-0873-4dfe-9afe-22926222b4fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>StyledButton-sc-1lpnvbj cryQQO mt-36 mt-36</value>
      <webElementGuid>151e918e-f1f6-473f-8b81-a845b8180594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1e01ac73-e98e-4def-bba6-cfb34a98925f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ถัดไป</value>
      <webElementGuid>689f1c8c-1410-4b57-902e-cfe7d7dbaa60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/div[@class=&quot;content&quot;]/div[1]/div[@class=&quot;sc-1w7x3ft-0 haqBKz&quot;]/div[@class=&quot;sc-1ijt930-0 kpohkU&quot;]/form[1]/div[@class=&quot;BaseGap-sc-1wadqs8 dzKCbJ sc-1ijt930-1 bnMtCQ font-highlight rg16 sc-1ijt930-1 bnMtCQ font-highlight rg16&quot;]/button[@class=&quot;StyledButton-sc-1lpnvbj cryQQO mt-36 mt-36&quot;]</value>
      <webElementGuid>75011e49-b88f-47f1-9e6b-ce9940d37650</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[2]</value>
      <webElementGuid>94c78d0c-7f05-4e8b-9d8f-76e6c8c90671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='body']/div[2]/div/div/div/form/div/button</value>
      <webElementGuid>323c508d-8834-41d0-b435-40b5bafd2c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ไม่ระบุ'])[1]/following::button[1]</value>
      <webElementGuid>281493b2-323d-4efd-a81e-0533dae72403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='หญิง'])[1]/following::button[2]</value>
      <webElementGuid>40d12da3-a03b-4572-b8cf-21b90b72f3a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Share'])[1]/preceding::button[1]</value>
      <webElementGuid>18fc146c-57f8-422d-bf98-d2349ee86f88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/button</value>
      <webElementGuid>0730be46-a472-48b2-99e7-a9633733df40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'ถัดไป' or . = 'ถัดไป')]</value>
      <webElementGuid>6e985b1f-d699-4da6-9745-8e51cd94d46e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
