<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__name</name>
   <tag></tag>
   <elementGuidId>a03eb0d1-f707-4e65-88b3-994fcc996042</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;name&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>57060b7b-263e-44eb-84ad-89811ed816f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>InputStyled-sc-9199qm iZdxpO font-highlight font-highlight</value>
      <webElementGuid>20c02710-41c3-48d2-a892-ecbb97a6bc44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>4f722101-732d-4334-aaf7-5610f4154ac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>52de7551-ff59-4d30-a5e9-bbef0138e0be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/div[@class=&quot;content&quot;]/div[1]/div[@class=&quot;sc-1w7x3ft-0 haqBKz&quot;]/div[@class=&quot;sc-1ijt930-0 kpohkU&quot;]/form[1]/div[@class=&quot;BaseGap-sc-1wadqs8 dzKCbJ sc-1ijt930-1 bnMtCQ font-highlight rg16 sc-1ijt930-1 bnMtCQ font-highlight rg16&quot;]/div[@class=&quot;BaseGap-sc-1wadqs8 itjsHI&quot;]/div[@class=&quot;TextFieldContainer-sc-mtgtrr bwLwNZ font-highlight font-highlight&quot;]/div[@class=&quot;relative&quot;]/input[@class=&quot;InputStyled-sc-9199qm iZdxpO font-highlight font-highlight&quot;]</value>
      <webElementGuid>7d01bc6f-42ef-44fc-be77-7baf645b54f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='name']</value>
      <webElementGuid>a76025ff-2fbd-456b-9786-be5465ebaece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='body']/div[2]/div/div/div/form/div/div[2]/div[2]/div/input</value>
      <webElementGuid>37dd6dfa-419a-474e-8a4d-6db9ee295dbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>7a431ca9-7a2d-41fd-808c-fda6bcc843ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'name']</value>
      <webElementGuid>d0929ca0-ac21-4844-be11-be74764306a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
