<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__password</name>
   <tag></tag>
   <elementGuidId>114b08a9-6ba5-494e-b8fc-fe0105e434c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;password&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d35142e6-c712-4a82-85ba-345f94fd3bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>InputStyled-sc-9199qm bODeUa font-highlight font-highlight</value>
      <webElementGuid>792d6e83-0f4b-47ca-9c37-b504027cacf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>45d9a701-90cf-47b9-96ae-5df34acb39dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>66d55e38-3d30-4914-a981-60a3916927e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>efbcc948-f977-4d74-80df-76306565ba93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>03471475-6805-4b1f-9469-82821d1adf13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0266d284-4589-489e-8625-c2c833a8f813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/div[@class=&quot;content&quot;]/div[1]/div[@class=&quot;sc-1w7x3ft-0 haqBKz&quot;]/div[@class=&quot;sc-1ijt930-0 kpohkU&quot;]/form[@class=&quot;font-highlight&quot;]/div[@class=&quot;BaseGap-sc-1wadqs8 ixYUFD&quot;]/div[@class=&quot;TextFieldContainer-sc-mtgtrr bwLwNZ font-highlight font-highlight&quot;]/div[@class=&quot;relative&quot;]/input[@class=&quot;InputStyled-sc-9199qm bODeUa font-highlight font-highlight&quot;]</value>
      <webElementGuid>ae55191a-aea4-4d29-83bb-e27b9fc282fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='password']</value>
      <webElementGuid>498d51be-a0c7-464c-be61-5d1eeeb6efc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='body']/div[2]/div/div/div/form/div[2]/div/div/input</value>
      <webElementGuid>e692d2a9-8d20-47f5-9831-9100500de000</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>25d126b2-af66-43b4-9b36-1b29ca53f5fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'password' and @type = 'password']</value>
      <webElementGuid>0718e5be-606f-4922-a686-3a741406416a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
