<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose File_email</name>
   <tag></tag>
   <elementGuidId>b8bb230f-056b-4e8e-9502-30ce4544f0a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98bea81c-49c0-4acb-ae52-6548bdc383b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>InputStyled-sc-9199qm bODeUa font-highlight font-highlight</value>
      <webElementGuid>6013a472-830f-4c19-8036-62eaf72c216e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>b8db0888-e868-4bfa-bd17-41fdb66cb5fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>ac755a03-1bf7-483b-a515-f50949cceae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;body&quot;)/div[@class=&quot;content&quot;]/div[1]/div[@class=&quot;sc-1w7x3ft-0 haqBKz&quot;]/div[@class=&quot;sc-1ijt930-0 kpohkU&quot;]/form[1]/div[@class=&quot;BaseGap-sc-1wadqs8 dzKCbJ sc-1ijt930-1 bnMtCQ font-highlight rg16 sc-1ijt930-1 bnMtCQ font-highlight rg16&quot;]/div[@class=&quot;BaseGap-sc-1wadqs8 itjsHI&quot;]/div[@class=&quot;TextFieldContainer-sc-mtgtrr bwLwNZ font-highlight font-highlight&quot;]/div[@class=&quot;relative&quot;]/input[@class=&quot;InputStyled-sc-9199qm bODeUa font-highlight font-highlight&quot;]</value>
      <webElementGuid>85a2e40b-c3ab-4d9f-8e78-404a3b83e72a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
      <webElementGuid>f2bec747-37d3-4cf0-817d-3e10de47c983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='body']/div[2]/div/div/div/form/div/div[2]/div/div/input</value>
      <webElementGuid>628139d7-9c46-485a-ba73-63d621bc29f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>20389aea-7f17-42e9-ba4c-3887a50e8b30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'email']</value>
      <webElementGuid>919ab693-26f7-423f-abbc-9ad18036d795</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
