<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ButtonRegister</name>
   <tag></tag>
   <elementGuidId>72a6ce2e-05ea-46f9-9151-ad98122e98fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnRegister</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnRegister']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7239da19-9e35-498c-b9fa-1fa2568b171e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5081a572-bc98-4d86-89e9-4f70e6d4a382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submit-button btn btn-block btn-secondary my-4 mx-auto fuse-ripple-ready</value>
      <webElementGuid>f650f881-a08e-4aa7-a08a-de9c8f7b9837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnRegister</value>
      <webElementGuid>111fe452-f770-4c5c-b5cc-d5d316e930e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                ลงทะเบียน
            </value>
      <webElementGuid>653c4473-d485-4974-adcc-71057ec0c885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnRegister&quot;)</value>
      <webElementGuid>d5b18fba-c408-4384-a921-ff24210b9ec8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnRegister']</value>
      <webElementGuid>52d9c3de-fdfb-4823-9d6a-10922389b562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmRegister']/button</value>
      <webElementGuid>ef38e377-6889-4eae-8e21-3cdaa87c6d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='เงื่อนไขการใช้บริการ'])[1]/following::button[1]</value>
      <webElementGuid>df16b621-cc1b-4317-83d4-00f424c46f6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ประกาศการประมวลผลข้อมูลส่วนบุคคล'])[1]/following::button[1]</value>
      <webElementGuid>3602bfe0-08d0-400d-ac0b-153a9a317905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='คุณมีบัญชีกับเราแล้ว?'])[1]/preceding::button[1]</value>
      <webElementGuid>3a6e5409-c713-4fdc-8381-64021d13778d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ล็อคอิน'])[1]/preceding::button[1]</value>
      <webElementGuid>bad3ed13-43cd-49b7-bc87-ada1daeff95f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ลงทะเบียน']/parent::*</value>
      <webElementGuid>dc4054bf-6220-4d05-8c1e-785eca50934d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>200f70bb-1567-4b9a-888b-4f174842f26f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'btnRegister' and (text() = '
                ลงทะเบียน
            ' or . = '
                ลงทะเบียน
            ')]</value>
      <webElementGuid>441331e2-384a-4fc4-a9cd-64e34404062a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
