<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>4a8badda-905b-4219-b6bc-bd79dc37256b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnRegister</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnRegister']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9f1265e8-b58e-4c98-a2fc-a49664604574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>459c899c-71a3-49ee-8ede-2ae80b33bfd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submit-button btn btn-block btn-secondary my-4 mx-auto fuse-ripple-ready</value>
      <webElementGuid>4b2991af-73b4-4160-adac-049f1fb9091f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnRegister</value>
      <webElementGuid>eaf296bd-93e8-4c92-aa45-25c6f1d77713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                ลงทะเบียน
            </value>
      <webElementGuid>193f8ee9-6dc6-400b-a854-c6e10e83a2c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnRegister&quot;)</value>
      <webElementGuid>a4e0de8d-c302-4f66-b442-89f3ce96c0ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnRegister']</value>
      <webElementGuid>6c8a6694-2ae8-47ef-996b-ada80a19d322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmRegister']/button</value>
      <webElementGuid>a2d49f7c-d17a-4c42-bcda-60c9d7c4edbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='เงื่อนไขการใช้บริการ'])[1]/following::button[1]</value>
      <webElementGuid>154225ef-7b1c-4535-9365-443e87a39b20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ประกาศการประมวลผลข้อมูลส่วนบุคคล'])[1]/following::button[1]</value>
      <webElementGuid>df17cecd-c3f6-464f-9369-689ea3d7d5d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='คุณมีบัญชีกับเราแล้ว?'])[1]/preceding::button[1]</value>
      <webElementGuid>44190a94-17dc-4d40-b5e9-3f6e8c4d001e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ล็อคอิน'])[1]/preceding::button[1]</value>
      <webElementGuid>eb62af46-d664-42d7-bbdb-820ce146c2ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ลงทะเบียน']/parent::*</value>
      <webElementGuid>7eaa6dcc-3c8a-4f37-8626-e418c5801267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>4afe668e-3a9c-4b29-bd45-60b431670966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'btnRegister' and (text() = '
                ลงทะเบียน
            ' or . = '
                ลงทะเบียน
            ')]</value>
      <webElementGuid>e1f4bab4-738a-4c76-9404-c07ee30ed8e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
