<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ClicksurName</name>
   <tag></tag>
   <elementGuidId>de032b45-c320-4723-875d-41042038a077</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>#select2-title_id-result-sf5f-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>#select2-title_id-result-sf5f-1</value>
      <webElementGuid>093e5b38-ed1b-4443-8728-f70a99067baf</webElementGuid>
   </webElementProperties>
</WebElementEntity>
