<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon__icon-eye-off toggle-password</name>
   <tag></tag>
   <elementGuidId>9c3f108b-c384-46ed-b501-199ac6289852</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>icon.icon-eye-off.toggle-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmRegister']/div[6]/div/div/div/icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>5a69c33f-0be0-4353-b1b7-58f2d4ff3981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-eye-off toggle-password</value>
      <webElementGuid>af6a0125-7012-4897-9165-1bceefbcbb7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmRegister&quot;)/div[@class=&quot;form-row&quot;]/div[@class=&quot;form-group col-md-6&quot;]/div[@class=&quot;input-data w-100&quot;]/div[@class=&quot;input-group&quot;]/icon[@class=&quot;icon-eye-off toggle-password&quot;]</value>
      <webElementGuid>65a8bf12-4944-46a6-847a-f9ca5c4512f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmRegister']/div[6]/div/div/div/icon</value>
      <webElementGuid>89aa543c-fffa-4696-b3cc-b1ada0908379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//icon</value>
      <webElementGuid>2e68e502-1497-479f-8d58-b70342937450</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
