<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon__toggle-password icon-eye-off</name>
   <tag></tag>
   <elementGuidId>5d322f7e-cbd9-481a-8e1c-c143fd53586b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>icon.toggle-password.icon-eye-off</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmRegister']/div[6]/div/div/div/icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>81d35ec3-1725-4205-ad69-ee0afe5fb8a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>toggle-password icon-eye-off</value>
      <webElementGuid>52ed13d2-47b2-4c8b-91e3-d179d8d68c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmRegister&quot;)/div[@class=&quot;form-row&quot;]/div[@class=&quot;form-group col-md-6&quot;]/div[@class=&quot;input-data w-100&quot;]/div[@class=&quot;input-group&quot;]/icon[@class=&quot;toggle-password icon-eye-off&quot;]</value>
      <webElementGuid>4235ac48-077a-49e8-b06a-1a12766bb1da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmRegister']/div[6]/div/div/div/icon</value>
      <webElementGuid>5150366c-016c-4e62-bfe5-b304b98f73a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//icon</value>
      <webElementGuid>b868e885-e967-4751-a300-fca8aa5992ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
