<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon__icon-eye-off toggle-confirm-password</name>
   <tag></tag>
   <elementGuidId>7218ad5a-5e74-4826-b2a0-1ab2b110a1dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>icon.icon-eye-off.toggle-confirm-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frmRegister']/div[6]/div[2]/div/div/icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>14ab1c69-fc0a-4bcc-982c-6156d2d2185f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon-eye-off toggle-confirm-password</value>
      <webElementGuid>fd76d626-f502-40fa-9615-f0004242c18b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmRegister&quot;)/div[@class=&quot;form-row&quot;]/div[@class=&quot;form-group col-md-6&quot;]/div[@class=&quot;input-data w-100&quot;]/div[@class=&quot;input-group&quot;]/icon[@class=&quot;icon-eye-off toggle-confirm-password&quot;]</value>
      <webElementGuid>39e2d614-6f7d-44ee-9b3d-106f16945b0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmRegister']/div[6]/div[2]/div/div/icon</value>
      <webElementGuid>b2940a86-3b71-4b34-b27e-8706d8bd603d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/icon</value>
      <webElementGuid>6b7f2b65-5182-468f-bfaa-75be1cd83aa5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
