<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li__1</name>
   <tag></tag>
   <elementGuidId>6dcd1e8e-7b4f-4e02-aa0f-801246dddc95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-title_id-result-80d5-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='select2-title_id-result-80d5-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>11d200b5-13fb-46fe-b08b-1c6d8b782847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-results__option select2-results__option--highlighted</value>
      <webElementGuid>2b6f5066-7bb8-4c10-b628-1065c52c71d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-title_id-result-80d5-2</value>
      <webElementGuid>a93c6183-af55-43a4-98b7-bcb7f46b2021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>treeitem</value>
      <webElementGuid>08f25e0c-bc62-4bb3-b19a-b88cc473ef57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1a07f355-d96e-45db-88c2-e3f95ee63493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-select2-id</name>
      <type>Main</type>
      <value>select2-title_id-result-80d5-2</value>
      <webElementGuid>90d798a9-65ee-48fb-aaf6-c84a4a0ccae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>นาง</value>
      <webElementGuid>ff091fbc-f661-4aec-a9e3-fff3610b6e4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-title_id-result-80d5-2&quot;)</value>
      <webElementGuid>4080f584-13dd-4a08-bba1-42a095885b44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='select2-title_id-result-80d5-2']</value>
      <webElementGuid>537eab23-6185-4414-a2b1-f72af13a1020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select2-title_id-results']/li[3]</value>
      <webElementGuid>b4fedb40-5a0a-44ae-936d-41765c17d5ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='นาย'])[3]/following::li[1]</value>
      <webElementGuid>fce2e12d-541b-4529-b15e-71aaf6c7f654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='คำนำหน้าชื่อ'])[3]/following::li[2]</value>
      <webElementGuid>f5c28629-d263-4342-9130-6e7937ff56c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='นางสาว'])[2]/preceding::li[1]</value>
      <webElementGuid>35c8f113-e532-4a15-862b-a52ddd634a83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ด.ช.'])[2]/preceding::li[2]</value>
      <webElementGuid>fd04ace3-0ca3-4d98-84c7-34549ee39f11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]</value>
      <webElementGuid>20429aa2-9a2c-4790-afbd-048cfca757b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'select2-title_id-result-80d5-2' and (text() = 'นาง' or . = 'นาง')]</value>
      <webElementGuid>51cf8330-bf26-4766-a5cb-ae17a1bb0b4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
