<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_</name>
   <tag></tag>
   <elementGuidId>33d4f4fe-b5ee-482c-8d12-09673bbd1ce6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gender</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='gender']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>01284542-6705-4226-8b8c-76556f7f99cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gender</value>
      <webElementGuid>cbd16e15-9319-4405-a5c7-39473946bbcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d33efd2b-699f-46c0-b69b-2cdd28594e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>570ae6d1-4899-4f02-bde3-1073c7632f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>gender</value>
      <webElementGuid>319ce46f-7d84-475e-9969-f1df1a31a470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>                            
                            ชาย
                            หญิง
                            ไม่ระบุ                            
                        </value>
      <webElementGuid>97362d43-40f9-45e5-a5b8-31dc04876ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gender&quot;)</value>
      <webElementGuid>7dc93588-4ed3-45de-bfc0-c7fc98df1c85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='gender']</value>
      <webElementGuid>5ed8a726-4c9f-4d4e-bebb-eb10f3819ec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmRegister']/div[4]/div/div/select</value>
      <webElementGuid>9f2929ac-c643-48c7-93d5-7ae65a988ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='เพศ'])[1]/following::select[1]</value>
      <webElementGuid>f947bbc8-42bf-4dd6-9d29-1e90cf2bdf5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='นามสกุล'])[1]/following::select[1]</value>
      <webElementGuid>28fb4df2-ba72-48aa-bc6b-13862823c7f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ปีเกิด'])[1]/preceding::select[1]</value>
      <webElementGuid>40a69a8c-28a2-4d82-9003-edc209edf2d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ปีเกิด'])[3]/preceding::select[2]</value>
      <webElementGuid>ab774547-714c-4755-81d3-4fe34a231fa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/select</value>
      <webElementGuid>560e34a6-2d72-4630-abb2-25ff33fe1d28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'gender' and @type = 'text' and @name = 'gender' and (text() = '                            
                            ชาย
                            หญิง
                            ไม่ระบุ                            
                        ' or . = '                            
                            ชาย
                            หญิง
                            ไม่ระบุ                            
                        ')]</value>
      <webElementGuid>8fb899ce-723c-460b-9922-a70786b25d2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
