<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select__1</name>
   <tag></tag>
   <elementGuidId>7b7e426c-57ab-40e5-a273-2d9f4dedaa19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#role_cd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='role_cd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5361ae9a-49b4-4143-bb24-888a921afeb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>role_cd</value>
      <webElementGuid>8638fae3-903e-4030-b534-cc9302dbfa38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select form-control </value>
      <webElementGuid>25cb0c8e-8262-47ab-8a8c-5d658fdfcc64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>role_cd</value>
      <webElementGuid>b1e8a324-f914-41b2-ae9d-4f53bbb0a21a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TEACHER</value>
      <webElementGuid>0c51d853-251c-42d4-a3e9-0884a52a56a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ประเภทผู้ใช้งาน</value>
      <webElementGuid>bebb0fd9-a017-4f9b-87d1-f3ab686111f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>                        
                        ประเภทผู้ใช้งาน                                                
                        ครู
                        ผู้ปกครอง/นักเรียน
                    </value>
      <webElementGuid>e8900423-092a-48f7-a4bd-06cfc9cbd167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;role_cd&quot;)</value>
      <webElementGuid>2f5c9c73-b02e-48c0-96e7-14266a10ece4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='role_cd']</value>
      <webElementGuid>5b2888d8-5e14-4d34-95f1-8db9ad208c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmRegister']/div[8]/div/select</value>
      <webElementGuid>39f9e0ea-886b-43c9-b816-779d70f7bf3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ประเภทผู้ใช้งาน'])[1]/following::select[1]</value>
      <webElementGuid>cee600c5-731f-4a99-81a7-4a0a627457bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='รหัสผ่านประกอบไปด้วยตัวหนังสือภาษาอังกฤษตัวเล็ก (a-z) ตัวใหญ่ (A-Z) หรือตัวเลข (0-9) ก็ได้'])[1]/following::select[1]</value>
      <webElementGuid>27a3e19e-ae2f-4088-bd27-6047e9fb07f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='โรงเรียน'])[1]/preceding::select[1]</value>
      <webElementGuid>66e153d0-8afb-4145-b04d-bf29f1a190d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='กรุณาเลือกรายการ'])[1]/preceding::select[2]</value>
      <webElementGuid>a862a409-99ae-48be-92b5-8b4538710f24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/select</value>
      <webElementGuid>6e7db1f1-dbb9-4b33-810d-32734fdec3b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'role_cd' and @name = 'role_cd' and @placeholder = 'ประเภทผู้ใช้งาน' and (text() = '                        
                        ประเภทผู้ใช้งาน                                                
                        ครู
                        ผู้ปกครอง/นักเรียน
                    ' or . = '                        
                        ประเภทผู้ใช้งาน                                                
                        ครู
                        ผู้ปกครอง/นักเรียน
                    ')]</value>
      <webElementGuid>b4fe74f2-80f7-4358-b382-1ff887dbd002</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
