<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>6c63caaa-32a0-46be-81ec-3ec77492f585</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-title_id-container</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;select2-title_id-container&quot;)[count(. | //span[@class = 'select2-selection__rendered' and @id = 'select2-title_id-container' and @role = 'textbox' and @aria-readonly = 'true' and @title = 'คำนำหน้าชื่อ' and (text() = 'คำนำหน้าชื่อ' or . = 'คำนำหน้าชื่อ')]) = count(//span[@class = 'select2-selection__rendered' and @id = 'select2-title_id-container' and @role = 'textbox' and @aria-readonly = 'true' and @title = 'คำนำหน้าชื่อ' and (text() = 'คำนำหน้าชื่อ' or . = 'คำนำหน้าชื่อ')])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>95cb3a51-7c1a-475b-b821-d2f812427034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>42fd834f-b440-4fa8-9e62-53aedce9e46a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-title_id-container</value>
      <webElementGuid>3af91f6a-cfda-4cad-bcb4-1ba5a94079c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>be612fc9-02ea-4ea1-a06c-8bb6b4c1540a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>02d6810c-f332-41aa-8ce3-de7af9d496ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>คำนำหน้าชื่อ</value>
      <webElementGuid>464ca676-f2c9-4118-864d-1fe026e1b537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>คำนำหน้าชื่อ</value>
      <webElementGuid>7d6cb799-d26d-494b-b503-ad5ba5926ff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-title_id-container&quot;)</value>
      <webElementGuid>e09f3b0b-fb9d-4e8a-8cb7-6f0852782d93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-title_id-container']</value>
      <webElementGuid>4619243a-9bb4-4bbd-b6b0-751899862376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmRegister']/div[2]/div/span/span/span/span</value>
      <webElementGuid>4431f063-b5b4-420f-affb-eb2660d97a0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='คำนำหน้าชื่อ'])[1]/following::span[4]</value>
      <webElementGuid>3898eabc-a423-470f-9f1b-2f9424b2b2cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ข้อมูลทั่วไป'])[1]/following::span[4]</value>
      <webElementGuid>65a3c46d-3629-469d-92d2-ae13ac1a87e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ชื่อ'])[1]/preceding::span[3]</value>
      <webElementGuid>e27c5b24-19ba-459a-944d-8f40d067da6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='นามสกุล'])[1]/preceding::span[3]</value>
      <webElementGuid>6ccc549e-d8c6-4e58-adb2-371c5d4f09f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span/span</value>
      <webElementGuid>0992101d-8c10-4241-9c8c-239252f3c733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-title_id-container' and @title = 'คำนำหน้าชื่อ' and (text() = 'คำนำหน้าชื่อ' or . = 'คำนำหน้าชื่อ')]</value>
      <webElementGuid>230e95de-40d7-4222-b9cf-c1fdb703799c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
