<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_2546</name>
   <tag></tag>
   <elementGuidId>1132d0c7-fcfe-470e-bfab-e8817496761c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#select2-birth_year-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='select2-birth_year-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b5b9156e-f0e3-4109-9a13-d5b6cc030be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>231a5036-6ce9-446d-b154-738c36ebaa51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-birth_year-container</value>
      <webElementGuid>543e4a07-d1d6-4b36-b16a-36d5001ca42d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>156ceed9-7f34-4289-8d8f-2c0e0eaaca39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6fdb038a-9021-47ca-aa52-fe95a9861c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>2546</value>
      <webElementGuid>f2e0d686-9cf8-46f8-9df5-a47a6308a3fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2546</value>
      <webElementGuid>b251d751-0ecb-42af-9c7e-b84877c893eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select2-birth_year-container&quot;)</value>
      <webElementGuid>ae839567-1d02-4167-8023-6579bb3fa4ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='select2-birth_year-container']</value>
      <webElementGuid>76aec5ae-6aa9-4f22-b1b9-fb76fa5d96c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmRegister']/div[4]/div[2]/div/span/span/span/span</value>
      <webElementGuid>947c8d82-6d21-4cd9-a472-fb590f853fcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ปีเกิด'])[1]/following::span[4]</value>
      <webElementGuid>780646dd-e53c-40b0-919d-305390257d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='เพศ'])[1]/following::span[4]</value>
      <webElementGuid>4aef566c-b2a4-4150-afd3-151f5e3cbf3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='อีเมล'])[1]/preceding::span[3]</value>
      <webElementGuid>4df498d7-80ff-41de-b1c9-497438678c73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='โทรศัพท์มือถือ'])[1]/preceding::span[3]</value>
      <webElementGuid>bafc0d1d-5db1-4a6c-a132-fbe3eac88af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/span/span/span/span</value>
      <webElementGuid>95966b5f-6065-4c85-97d0-75f5aa25788b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-birth_year-container' and @title = '2546' and (text() = '2546' or . = '2546')]</value>
      <webElementGuid>234380f8-a6c0-40b0-9ffc-965d45781732</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
