<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>62644700-6aa9-4f41-83c0-9deb7ed58e6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnAcceptPDPA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnAcceptPDPA']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>24682ae7-2902-4a66-9df6-4baf1b74b956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>002d73ba-9fe3-4c57-9c33-1d75c8be4b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnAcceptPDPA</value>
      <webElementGuid>5818a4cc-d444-4e0e-8fb3-cbba095ef2eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>runat</name>
      <type>Main</type>
      <value>server</value>
      <webElementGuid>6cbf7edb-3f0d-44b1-974f-884454b06ffa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>clientidmode</name>
      <type>Main</type>
      <value>static</value>
      <webElementGuid>1776c9b6-2f96-4dea-9868-354b5fa28bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary close_cookie order-12 order-md-1</value>
      <webElementGuid>c3aa0c25-48ab-4435-a3e1-092e219c30c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>hwc_PDPA.acceptAllCookies();</value>
      <webElementGuid>2c0b5136-25b6-488f-bd1b-2cf62162340d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ตกลงทั้งหมด</value>
      <webElementGuid>e0bf09f5-d5fc-436b-9561-245fa661708b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnAcceptPDPA&quot;)</value>
      <webElementGuid>96f35033-363c-4a8c-b244-76fce83aed48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnAcceptPDPA']</value>
      <webElementGuid>4f236185-d28f-4bd5-8b79-306256d9f6b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cookieModal']/div/div/div[3]/div/button[2]</value>
      <webElementGuid>46c079f4-4150-4c5e-87b2-99e031bf7c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ตั้งค่าคุกกี้'])[1]/following::button[1]</value>
      <webElementGuid>59f6a085-b9f8-436d-9f37-b124eee9461e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ประกาศการใช้งานคุกกี้'])[1]/following::button[2]</value>
      <webElementGuid>396753b1-74f5-4bb4-a546-25f3433afbf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='การตั้งค่าคุกกี้'])[1]/preceding::button[1]</value>
      <webElementGuid>f3dec9da-0e8e-4cb0-9055-71bb83c392db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='การตั้งค่าคุกกี้'])[2]/preceding::button[2]</value>
      <webElementGuid>911810e0-3364-4bd8-8acc-eedac4c47284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ตกลงทั้งหมด']/parent::*</value>
      <webElementGuid>1411f53e-7fa3-465d-a865-4328e3cbe036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>3adc64dd-b245-4b92-8e82-2035dd9216be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnAcceptPDPA' and (text() = 'ตกลงทั้งหมด' or . = 'ตกลงทั้งหมด')]</value>
      <webElementGuid>8ee0a7ec-353d-4de3-b409-730ea70d6cd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
