<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__form-Krungsri_NOW-8b12.LastName.Value</name>
   <tag></tag>
   <elementGuidId>0be4b73c-f527-4462-884e-0491b9882a5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#form-Krungsri_NOW-8b12_LastName_Value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='form-Krungsri_NOW-8b12_LastName_Value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>18e030f6-ab22-427f-85f5-298ea0257036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>49adb89d-dd24-4c83-93b3-821d02ded83f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form-Krungsri_NOW-8b12_LastName_Value</value>
      <webElementGuid>ba8ecce6-fb78-469e-bd36-21c00061bced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form-Krungsri_NOW-8b12.LastName.Value</value>
      <webElementGuid>fb53725e-7b0c-4764-866d-f2697416af95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>นามสกุล*</value>
      <webElementGuid>768c7a9c-0f61-49f2-aacc-b7819955df55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6226e4d2-c3ea-467e-8073-3a7a679c2418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-Krungsri_NOW-8b12_LastName_Value&quot;)</value>
      <webElementGuid>97472e9e-b247-4256-a1d7-334fc41e183d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form-Krungsri_NOW-8b12_LastName_Value']</value>
      <webElementGuid>21e8bf19-854d-44cd-81f6-893ff5fac503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-Krungsri_NOW-8b12']/div/div[2]/div/input</value>
      <webElementGuid>865b0bed-4f50-41c2-807b-70f5b210469b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>c94199e5-d77f-417d-9ef9-db4b18e0ad17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'form-Krungsri_NOW-8b12_LastName_Value' and @name = 'form-Krungsri_NOW-8b12.LastName.Value' and @placeholder = 'นามสกุล*' and @type = 'text']</value>
      <webElementGuid>059d8d6a-6dad-417d-b9af-9055e4f695f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
