<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__form-Krungsri_NOW-8b12.Phone.Value</name>
   <tag></tag>
   <elementGuidId>c9c12d97-9008-4714-b571-4d17d777764c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#form-Krungsri_NOW-8b12_Phone_Value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='form-Krungsri_NOW-8b12_Phone_Value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f0c4288-ff6c-4d9b-b84e-667c279b5ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a3fc5896-de84-4f73-89dd-23981a0648eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form-Krungsri_NOW-8b12_Phone_Value</value>
      <webElementGuid>36cf071a-575a-448a-8e6b-997991031601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form-Krungsri_NOW-8b12.Phone.Value</value>
      <webElementGuid>62955304-f816-4640-ac79-7e4756c289cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>เบอร์โทรศัพท์มือถือ*</value>
      <webElementGuid>d0d37d90-5710-42be-8e3d-eae7b0e0084b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6db60855-2abf-4dbd-be11-9c062224caf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-Krungsri_NOW-8b12_Phone_Value&quot;)</value>
      <webElementGuid>d467c27e-a151-4ac5-925d-99e0949404c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form-Krungsri_NOW-8b12_Phone_Value']</value>
      <webElementGuid>b7155662-6265-4366-ae06-ebea69c0475c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-Krungsri_NOW-8b12']/div/div[3]/div/input</value>
      <webElementGuid>93b11faa-a362-43ed-9199-301848dd60fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>d0a3b8e4-8351-4895-ac97-2ccfda0a16c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'form-Krungsri_NOW-8b12_Phone_Value' and @name = 'form-Krungsri_NOW-8b12.Phone.Value' and @placeholder = 'เบอร์โทรศัพท์มือถือ*' and @type = 'text']</value>
      <webElementGuid>137457e9-a19b-4d4b-a42b-366dbaf987a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
