<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__form-Krungsri_NOW-8b12.FirstName.Value</name>
   <tag></tag>
   <elementGuidId>95c8a641-89e9-4b28-b8fc-dfc10d4033e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#form-Krungsri_NOW-8b12_FirstName_Value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='form-Krungsri_NOW-8b12_FirstName_Value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2e614ba-41ea-4ebe-bb7e-d0abee5206c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>25c10cb8-1679-42b0-948f-e76a81eeda0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form-Krungsri_NOW-8b12_FirstName_Value</value>
      <webElementGuid>791d68ce-426a-409a-a7dc-7ac3d2b1a6c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>form-Krungsri_NOW-8b12.FirstName.Value</value>
      <webElementGuid>d1bbf59a-c3f9-4742-b197-8747acc223cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ชื่อ*</value>
      <webElementGuid>d3a8ab1b-4a74-4ee6-b30d-ffbe5e45085c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>011c2808-12f2-40d4-9a73-a68dcc3a04ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-Krungsri_NOW-8b12_FirstName_Value&quot;)</value>
      <webElementGuid>f3234207-a3fe-437c-9239-c79f9f919b50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='form-Krungsri_NOW-8b12_FirstName_Value']</value>
      <webElementGuid>5874c5a7-0911-426f-9003-c8fbf06f7c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-Krungsri_NOW-8b12']/div/div/div/input</value>
      <webElementGuid>29a85b79-def3-4a1e-b18f-6dee9f482446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>32978bb3-8329-4ca5-8228-08b1289eb360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'form-Krungsri_NOW-8b12_FirstName_Value' and @name = 'form-Krungsri_NOW-8b12.FirstName.Value' and @placeholder = 'ชื่อ*' and @type = 'text']</value>
      <webElementGuid>655396a8-7b5e-4e27-9780-5a671e6fa682</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
