<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>0cc379b3-34f6-4044-aec0-e1e1affcba02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.dropdown-item.is-hovered</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/div/div/div/form/div/div/div[3]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3fd122ec-bf56-4fbb-b0f9-f789b57788e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item is-hovered</value>
      <webElementGuid>745f8ef9-ef7d-43d8-b18a-280545d04bf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                  นาย
                  </value>
      <webElementGuid>dc92bec6-72c0-48a3-b144-d785ddec21df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;airpaz-desktop-layout&quot;]/div[@class=&quot;signup-container&quot;]/div[@class=&quot;auth-form-wrapper is-flex flex-col items-center&quot;]/div[@class=&quot;signup-form-wrapper panel&quot;]/div[@class=&quot;panel-block is-block is-relative&quot;]/form[@class=&quot;signup-form&quot;]/div[@class=&quot;field input-title&quot;]/div[@class=&quot;control picker has-icons-right is-active is-focused is-borderless&quot;]/div[@class=&quot;dropdown-menu&quot;]/ul[@class=&quot;dropdown-content&quot;]/li[1]/a[@class=&quot;dropdown-item is-hovered&quot;]</value>
      <webElementGuid>01fc44a3-bdd2-4588-b935-f3e50548cc86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/div/div/div/form/div/div/div[3]/ul/li/a</value>
      <webElementGuid>b33019cb-cab6-4aa5-a4f5-6be11468a908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'นาย')]</value>
      <webElementGuid>e73f5a35-7496-4807-990b-4c71a674c864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='นาย'])[1]/following::a[1]</value>
      <webElementGuid>5db7bdbf-4e15-4405-afb6-b9038f93358e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='คำนำหน้า'])[1]/following::a[1]</value>
      <webElementGuid>7250b9bb-dad4-450d-b50d-46d2937a0e92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='นาง'])[1]/preceding::a[1]</value>
      <webElementGuid>7058867b-dce1-45d8-ae7f-f2532713d7c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='นางสาว'])[1]/preceding::a[2]</value>
      <webElementGuid>3a0e4273-2e74-40fa-b564-45b402719b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>91b20316-50e9-4aef-81e2-d24b430fe8de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '
                  นาย
                  ' or . = '
                  นาย
                  ')]</value>
      <webElementGuid>f95af71a-c6b7-47e4-9b3f-db14e62ec449</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
