<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__check</name>
   <tag></tag>
   <elementGuidId>e3350a1c-24dc-45f7-b992-d833fb676e1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.check</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/div/div/div/form/div[5]/label/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7c4fdb9d-fc35-446e-b8af-b0caff73a4f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>check</value>
      <webElementGuid>a6d2fe27-5b88-4794-ad81-80c70cd8c4f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;airpaz-desktop-layout&quot;]/div[@class=&quot;signup-container&quot;]/div[@class=&quot;auth-form-wrapper is-flex flex-col items-center&quot;]/div[@class=&quot;signup-form-wrapper panel&quot;]/div[@class=&quot;panel-block is-block is-relative&quot;]/form[@class=&quot;signup-form&quot;]/div[@class=&quot;control m-b-30&quot;]/label[@class=&quot;checkbox&quot;]/div[@class=&quot;check&quot;]</value>
      <webElementGuid>4fac0176-bbe6-48ed-af6b-f90bd3030b4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/div/div/div/form/div[5]/label/div</value>
      <webElementGuid>31441009-a715-47eb-ae08-d9d0e0701901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='อีเมล์'])[1]/following::div[3]</value>
      <webElementGuid>e3220065-7711-4dc1-b5ca-9d5589ecde3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='มือถือ'])[1]/following::div[5]</value>
      <webElementGuid>7d1f1975-459d-4ad6-83b0-7722a413f853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='สมัครสมาชิก'])[2]/preceding::div[6]</value>
      <webElementGuid>5f664d2b-de70-4487-bf4c-519c390f1ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='เข้าสู่ระบบด้วย Facebook'])[1]/preceding::div[7]</value>
      <webElementGuid>2fd5c59b-c738-467d-88f4-b1efea12b4cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
      <webElementGuid>8c597f46-ffb1-43f7-b83b-64ec0e522d07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
