<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__input_1_2</name>
   <tag></tag>
   <elementGuidId>71213753-9beb-45da-9a2f-723070e9c241</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.field.f-3 > div.control > input.input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f18d74f-aa24-4d98-afb4-d3e12bb152dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b4558553-b4e0-428a-95a7-e62dfcd81118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>mobile</value>
      <webElementGuid>71cc584a-7fef-4c1b-8e4b-05bdd88f3898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g. 81234567890</value>
      <webElementGuid>cb81c17f-ba8d-4ea0-9961-8cbe0efa087b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2bb9dfa-b0dc-4deb-a3c4-71066a901d68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[@class=&quot;airpaz-desktop-layout&quot;]/div[@class=&quot;signup-container&quot;]/div[@class=&quot;auth-form-wrapper is-flex flex-col items-center&quot;]/div[@class=&quot;signup-form-wrapper panel&quot;]/div[@class=&quot;panel-block is-block is-relative&quot;]/form[@class=&quot;signup-form&quot;]/div[@class=&quot;field-group&quot;]/div[@class=&quot;field f-3&quot;]/div[@class=&quot;control&quot;]/input[@class=&quot;input&quot;]</value>
      <webElementGuid>c5c715db-146e-4048-92a0-51c090d53f09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[4]</value>
      <webElementGuid>d8b11f63-c578-412b-ac0a-b7f2b83bc48d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/div/div/div/form/div[3]/div[2]/div/input</value>
      <webElementGuid>5cce596a-fcd3-4506-935c-7d9efe8aea89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/input</value>
      <webElementGuid>775e1ca6-7b6e-4b19-b846-d344bd83d9ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'e.g. 81234567890']</value>
      <webElementGuid>06a8e98f-09ba-4521-9057-301275477008</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
