<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__picker__nav--prev</name>
   <tag></tag>
   <elementGuidId>a655c618-ed26-4e96-b653-f0bc6f19ce80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.picker__nav--prev</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='P374426038_root']/div/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>21e3aa3e-0655-42f6-83a3-72e2a2ff2dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>picker__nav--prev</value>
      <webElementGuid>342fcf85-b4e5-403f-88d4-90ed8454df90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nav</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>25929309-36ea-4aac-9320-e26db302f1ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>510c385d-7bbf-4bc4-aafb-477508379514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>P374426038_table</value>
      <webElementGuid>57fd1029-db88-4f3e-b180-d77900be127b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Previous month</value>
      <webElementGuid>23971759-1e80-4eba-b41d-c7d846757af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P374426038_root&quot;)/div[@class=&quot;picker__holder&quot;]/div[@class=&quot;picker__frame&quot;]/div[@class=&quot;picker__wrap&quot;]/div[@class=&quot;picker__box&quot;]/div[@class=&quot;picker__header&quot;]/div[@class=&quot;picker__nav--prev&quot;]</value>
      <webElementGuid>e5cfde16-2d76-4776-8ed5-fd0b3244c69d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='P374426038_root']/div/div/div/div/div/div</value>
      <webElementGuid>2065fd54-a8a3-4dbb-a9ab-0102261b200f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='เข้าสู่ระบบ'])[1]/following::div[26]</value>
      <webElementGuid>2d6fa80c-d20b-40de-896b-5d8c68dec8a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='มีบัญชีสมาชิกอยู่แล้วใช่หรือไม่'])[1]/following::div[26]</value>
      <webElementGuid>83f4db39-fa46-4366-a7d8-4ebbf023bea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='อ.'])[1]/preceding::div[2]</value>
      <webElementGuid>ceae1556-5a3a-44fa-a7e5-510ca0bef06f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='จ.'])[1]/preceding::div[2]</value>
      <webElementGuid>776069ad-f4f8-47f7-806e-d5ad96989669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/div/div/div</value>
      <webElementGuid>13ccf732-34ef-4448-a2de-c546bbb53ed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'Previous month']</value>
      <webElementGuid>6f1cf3f6-dd24-457d-8733-29d25efd4722</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
