<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_17</name>
   <tag></tag>
   <elementGuidId>51c849f5-944d-4e0c-a90b-fcaf8347faf8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='P374426038_table']/tbody/tr[4]/td[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d9d2128c-6158-4bc8-8756-21b132a81df1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>picker__day picker__day--infocus</value>
      <webElementGuid>840d6f4c-8057-45ef-b4a2-218880c236dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pick</name>
      <type>Main</type>
      <value>1047834000000</value>
      <webElementGuid>d31f0806-3c1f-43f3-a6b4-a676f6733661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>fe40eab8-116f-4d17-a681-124946d17a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>17 มี.ค. 2003</value>
      <webElementGuid>cc662313-d719-4598-889a-f316998d0487</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>06939687-3fd4-431c-a1b8-6936c82dbd8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P374426038_table&quot;)/tbody[1]/tr[4]/td[2]/div[@class=&quot;picker__day picker__day--infocus&quot;]</value>
      <webElementGuid>5b131489-f46b-47ae-bd58-41f2c743a8b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='P374426038_table']/tbody/tr[4]/td[2]/div</value>
      <webElementGuid>0c9bcbe2-77b0-4558-9d0f-423d83b0ff40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ส.'])[1]/following::div[23]</value>
      <webElementGuid>596a63a4-f6ba-43d2-8110-719061bb90bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ศ.'])[1]/following::div[23]</value>
      <webElementGuid>0abd4d58-e2cb-4ae6-a667-734d8618d23d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::div[20]</value>
      <webElementGuid>cdd7734c-6b51-45c7-a3ba-6e18302e2da3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ชาย'])[1]/preceding::div[22]</value>
      <webElementGuid>cba526c6-edf6-46d2-ae23-6625f1cb08fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='17']/parent::*</value>
      <webElementGuid>69a233a7-176d-482b-98a3-9dd45d91fca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/div</value>
      <webElementGuid>260e0c51-db57-4e94-b462-78438f70714f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '17' or . = '17')]</value>
      <webElementGuid>3f5ddb10-f064-4746-8887-1af3b7815c94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
