<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_8</name>
   <tag></tag>
   <elementGuidId>702d2fd4-cf16-456a-9398-c3870473eb30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.picker__day.picker__day--infocus.picker__day--highlighted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='P2130874349_table']/tbody/tr[2]/td[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>de453026-d82d-4281-b2af-52015c58501c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>picker__day picker__day--infocus picker__day--highlighted</value>
      <webElementGuid>ed90ca4f-e491-4fae-a269-b81992392c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pick</name>
      <type>Main</type>
      <value>1365354000000</value>
      <webElementGuid>e8f9de7e-ae66-47df-bb19-1538952cdf8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>a76b7112-9e9d-4dd3-bb79-9003f3771c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>08 เม.ย. 2013</value>
      <webElementGuid>f4afe3a2-31ba-4541-b273-d83f0212327a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7300133f-2da1-48e1-89ea-366ce4144885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>e4913a92-2ede-4b99-a770-a2296f3dd07e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P2130874349_table&quot;)/tbody[1]/tr[2]/td[2]/div[@class=&quot;picker__day picker__day--infocus picker__day--highlighted&quot;]</value>
      <webElementGuid>660c97b5-050c-404c-9613-6e7a05f51fcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='P2130874349_table']/tbody/tr[2]/td[2]/div</value>
      <webElementGuid>e0603f52-621c-4e86-b983-5e729575f2fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ส.'])[1]/following::div[9]</value>
      <webElementGuid>95750eeb-5d9a-4134-9838-b1412e5f6497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ศ.'])[1]/following::div[9]</value>
      <webElementGuid>eab6b47d-3207-4d54-811d-3360aa9a57f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::div[34]</value>
      <webElementGuid>34c4f7b4-5b08-4a58-a606-d204adb43771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ชาย'])[1]/preceding::div[36]</value>
      <webElementGuid>9cedd1cc-6914-44f7-981d-f17ada6ceeb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='8']/parent::*</value>
      <webElementGuid>3e1f0c05-411d-4027-8fc0-f0f567488515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div</value>
      <webElementGuid>0cc588ad-1c63-48bd-8518-1721b148e613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '8' or . = '8')]</value>
      <webElementGuid>77728260-2ca4-4828-9ccd-7fd2c661d195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='P961780276_table']/tbody/tr[2]/td[2]/div</value>
      <webElementGuid>112a1ded-3d8f-4694-a653-c5bedfb15eeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='P1114657453_table']/tbody/tr[2]/td[2]/div</value>
      <webElementGuid>294bcd7f-0f3a-498f-9fa1-dc440e29806e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='P567387626_table']/tbody/tr[2]/td[2]/div</value>
      <webElementGuid>29efe25a-d79a-45cd-a281-44d2fc2555c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
