<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Close_icon fa fa-check</name>
   <tag></tag>
   <elementGuidId>7b35dcff-8db4-4bf0-a800-9807e31ad26f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.icon.fa.fa-check</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='signup']/div/div/div/div[2]/form/div[3]/div[2]/div/div/label/span/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b2ab75da-49bb-4401-b816-dbc0b85f6fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon fa fa-check</value>
      <webElementGuid>c8f6e051-bbbf-4ece-84bb-8b79639b6115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6c915d65-8fcc-4560-a57b-5eeb171f123b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signup&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-offset-1 col-md-10&quot;]/div[@class=&quot;bg-transparent&quot;]/form[@class=&quot;ng-dirty ng-valid-parse ng-invalid ng-invalid-maxlength&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;form-input&quot;]/div[@class=&quot;checkbox-inline&quot;]/div[@class=&quot;checkbox&quot;]/label[1]/span[@class=&quot;checkbox-style&quot;]/i[@class=&quot;icon fa fa-check&quot;]</value>
      <webElementGuid>9c6bd51b-d49c-429f-922b-f7fe1728e05f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='signup']/div/div/div/div[2]/form/div[3]/div[2]/div/div/label/span/i</value>
      <webElementGuid>7b1a2732-c56f-4044-980d-88ff95293a0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/i</value>
      <webElementGuid>7bda0a6c-8d7a-452d-a79f-03f1ebc2f14b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
