<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>47485750-2a1d-44ef-8909-489cd364c6fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.input-icon > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='signup']/div/div/div/div[2]/form/div[2]/div[2]/div/div[2]/span/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>be33ff5a-60f5-4e85-9dc3-852f54cb3e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.1112.com/images/form/calendar_form.svg</value>
      <webElementGuid>114738a0-4287-4b8f-8b78-f868601c9578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signup&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-offset-1 col-md-10&quot;]/div[@class=&quot;bg-transparent&quot;]/form[@class=&quot;ng-pristine ng-valid ng-valid-maxlength&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;form-input&quot;]/span[@class=&quot;input-icon&quot;]/img[1]</value>
      <webElementGuid>cdcd89f6-578b-4138-a704-44576458911f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='signup']/div/div/div/div[2]/form/div[2]/div[2]/div/div[2]/span/img</value>
      <webElementGuid>6441d1a5-bb09-41f9-999f-b1537bb6f4be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.1112.com/images/form/calendar_form.svg')]</value>
      <webElementGuid>4a566e2d-1ad6-441b-b2a2-36245b4c2ec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/span/img</value>
      <webElementGuid>3b1945b9-44ea-421f-a059-fc92950b48f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.1112.com/images/form/calendar_form.svg']</value>
      <webElementGuid>21fcb2b9-2de4-4ec8-8b24-c037851aac61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
