<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_dob</name>
   <tag></tag>
   <elementGuidId>f8eb9db0-24cf-4cbf-8442-d6b9e0d97245</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#P5217971</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;P5217971&quot;)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@ng-model='signupData.dob']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3d8dabe5-b4d1-4bc2-a966-780122d6a283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>signupData.dob</value>
      <webElementGuid>83a6e145-71d6-4cf8-8ad5-681a9c327618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control datepicker ng-pristine ng-valid picker__input ng-empty ng-valid-maxlength picker__input--active ng-touched picker__input--target</value>
      <webElementGuid>8284bd41-8ecf-435d-88c9-2fed359f9dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>f240b0ea-8a2d-418c-8099-2bd39976e738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>60986521-e642-4214-afe9-643826276034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dob</value>
      <webElementGuid>ffc4bf85-cc8b-4153-8584-76b956a6910e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>validateDOB()</value>
      <webElementGuid>6406aa2a-9fa4-4083-8b4c-acff93fe3d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>วัน / เดือน / ปีเกิด</value>
      <webElementGuid>27447845-383b-477c-b836-5947bc8e935d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>P5217971</value>
      <webElementGuid>89e325a1-0c83-4466-9cb4-61bf50c0bc7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>95153ff9-b805-44e5-a1e0-17d164bc8fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>77a6c37d-4ef6-4e4c-a788-a45eb1693d96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>db9bbe0a-04de-4e76-bd37-5d64af90d9e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>P5217971_root</value>
      <webElementGuid>131ddece-9a42-466f-b928-2814eafd5545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;P5217971&quot;)</value>
      <webElementGuid>5761a7c7-db74-4ce4-a75f-aa0454a05a97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='P5217971']</value>
      <webElementGuid>828cbdc3-46c3-417a-a421-ebf27cd69d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='signup']/div/div/div/div[2]/form/div[2]/div[2]/div/div[2]/input</value>
      <webElementGuid>406ce542-29e5-4c4d-90b4-f9fc5e5d2eaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/input</value>
      <webElementGuid>38914d75-1593-4d50-8ad5-aacf254de69d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'dob' and @placeholder = 'วัน / เดือน / ปีเกิด' and @id = 'P5217971']</value>
      <webElementGuid>7d2648e5-4c87-42bd-b4af-319fa752c4ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
