<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__customerEmail</name>
   <tag></tag>
   <elementGuidId>08e53ba8-43da-4a70-9947-21e81dd321b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;customerEmail&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='customerEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f68ec446-20d5-40b9-b4ff-20af98ccde64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-valid ng-empty ng-valid-maxlength</value>
      <webElementGuid>9486a97e-0ff7-475b-a4bd-e45a463d6923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b61bc5fa-fcaa-49ab-a6f5-4a4746462af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customerEmail</value>
      <webElementGuid>c02492cf-2201-4d5e-8657-444ede550ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>signupData.email</value>
      <webElementGuid>88c0d6a6-a676-4c41-85c1-fb4cf0c4173c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>validateEmail()</value>
      <webElementGuid>f15f560c-8b4f-4aaf-b545-1ded755d4ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>อีเมล</value>
      <webElementGuid>9285ee68-7cec-40fc-9f05-19410194b8dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>cdf102f2-1f63-48af-b96b-bd28c76f9b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>42834b9e-8c9a-4945-86b0-edb9ec479757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signup&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-offset-1 col-md-10&quot;]/div[@class=&quot;bg-transparent&quot;]/form[@class=&quot;ng-dirty ng-valid-parse ng-invalid ng-invalid-maxlength&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;form-input required&quot;]/input[@class=&quot;form-control ng-pristine ng-untouched ng-valid ng-empty ng-valid-maxlength&quot;]</value>
      <webElementGuid>96ac59fb-dcb6-4f85-b97a-6a4e1c398f5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='customerEmail']</value>
      <webElementGuid>c3057be6-b78e-49b8-970d-4c1367c8bb55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='signup']/div/div/div/div[2]/form/div[4]/div[2]/input</value>
      <webElementGuid>73391995-2a03-4106-9ec7-397c8cee7689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>d8d1efea-a477-4d3d-be0b-c8f5797b1a5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'customerEmail' and @placeholder = 'อีเมล']</value>
      <webElementGuid>e0d837f5-fe15-4446-8d9c-5db2aef6143e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
