<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__customerPhone</name>
   <tag></tag>
   <elementGuidId>ed617c23-87e5-4ce9-8c30-7c6d9acdfa7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;customerPhone&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='customerPhone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27d71fb8-630f-4254-877c-2e82dbc28899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-untouched ng-valid ng-valid-maxlength ng-not-empty ng-dirty ng-valid-parse</value>
      <webElementGuid>a197d19a-bb7c-4e08-ba39-b668769bd9bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4c34ac7e-e25d-45c1-932d-c3d8f939ab82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customerPhone</value>
      <webElementGuid>52f8ec60-99a2-4f37-8a66-2f4a058035e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>signupData.phone</value>
      <webElementGuid>64e6959e-6e48-4fd2-8af5-21356fa09069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>validatePhone(signupData.phone)</value>
      <webElementGuid>b5f7fd2b-7b48-450e-822c-cc0d125287bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>เบอร์โทรศัพท์มือถือ</value>
      <webElementGuid>a082b483-506e-4fec-a731-e5b5897e3e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>e6f89614-c0bc-4062-b4be-e892127dacce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signup&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-offset-1 col-md-10&quot;]/div[@class=&quot;bg-transparent&quot;]/form[@class=&quot;ng-valid ng-valid-maxlength ng-dirty ng-valid-parse&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;form-input required&quot;]/input[@class=&quot;form-control ng-untouched ng-valid ng-valid-maxlength ng-not-empty ng-dirty ng-valid-parse&quot;]</value>
      <webElementGuid>03bee862-10d9-48b5-ab14-aa7888ab3ca7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='customerPhone']</value>
      <webElementGuid>31404dff-f910-45f7-84b5-bcdad9a0fd75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='signup']/div/div/div/div[2]/form/div[2]/div/div/div[2]/input</value>
      <webElementGuid>fe216bea-760b-4613-96c8-cf4fd21c366b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/input</value>
      <webElementGuid>d8ae34eb-316e-4902-abe0-3a7038f4f892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'customerPhone' and @placeholder = 'เบอร์โทรศัพท์มือถือ']</value>
      <webElementGuid>2f8d0bd9-ace8-4069-a2f8-509e4a11c2b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
