<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Male_sex</name>
   <tag></tag>
   <elementGuidId>bf65853e-3da1-4d19-a04f-25abbdaf2aae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#u_4_5_gQ</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='u_4_5_gQ']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4c4e04e3-37d4-486c-884f-7d9623c8a51b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6379ff12-811c-4224-ad5f-e2b54f92886a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_8esa</value>
      <webElementGuid>6464a983-91b7-4f24-9218-83bcb2890cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sex</value>
      <webElementGuid>0f7b2c0e-7417-414e-9cf5-334a0a14740f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>0c26703b-74de-4496-b621-b774ff971985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u_4_5_gQ</value>
      <webElementGuid>15f7fdb4-fdf9-45a7-8ae5-02d947b50df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_4_5_gQ&quot;)</value>
      <webElementGuid>88089682-d22f-4994-ae81-91953727cf28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='u_4_5_gQ']</value>
      <webElementGuid>34558a0b-e089-476f-9ef1-415154762a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='u_4_o_bF']/span[2]/input</value>
      <webElementGuid>198e4ebc-2223-47e4-a925-1e62eb1576b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/input</value>
      <webElementGuid>1972ba2c-51fe-4ff4-8c8e-ade68af592c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'sex' and @id = 'u_4_5_gQ']</value>
      <webElementGuid>c588279b-9614-4633-a256-1c60700c7a44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
