<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_123456789101112131415161718192021222_566da4</name>
   <tag></tag>
   <elementGuidId>d3bc53b3-eb8f-45ee-aa9f-581b0b30d545</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#day</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='day']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b0656957-59ca-4f93-a090-a2c26236ceb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Day</value>
      <webElementGuid>14ade987-cc62-485a-b09a-4774a079b0a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>birthday_day</value>
      <webElementGuid>dc9ec200-f457-4552-99d1-ea5271e23c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>day</value>
      <webElementGuid>6716de9d-a18b-42e4-a3e7-44a641913df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Day</value>
      <webElementGuid>e08dc573-6877-467e-a0a5-2c6728db5319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_9407 _5dba _9hk6 _8esg</value>
      <webElementGuid>0377e66e-04c1-4f9f-88c1-821703f3bc33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12345678910111213141516171819202122232425262728293031</value>
      <webElementGuid>230cf936-d972-47e2-96c6-a35e7f754f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;day&quot;)</value>
      <webElementGuid>47a77bf5-df0b-4c0c-a116-04addbe0ec72</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='day']</value>
      <webElementGuid>f6cc8b84-5862-4403-b50b-41b366889394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='u_3_l_ix']/span/select</value>
      <webElementGuid>62ba64d2-325d-4206-98d4-0bfacf6eb203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of birth'])[1]/following::select[1]</value>
      <webElementGuid>56feb255-d039-459e-9434-fc9adc7adb70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('We couldn', &quot;'&quot;, 't create your accountWe were not able to sign you up for Facebook.')])[1]/following::select[1]</value>
      <webElementGuid>bc18b5e2-fd1b-489e-840e-f8bf0fbca598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Age'])[1]/preceding::select[3]</value>
      <webElementGuid>f2868759-9262-420b-bf22-fa5078c88343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender'])[1]/preceding::select[3]</value>
      <webElementGuid>22d675b6-95c6-4791-9d23-73e9592a5073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>828cd494-31ce-4c71-b167-9c3e61670e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'birthday_day' and @id = 'day' and @title = 'Day' and (text() = '12345678910111213141516171819202122232425262728293031' or . = '12345678910111213141516171819202122232425262728293031')]</value>
      <webElementGuid>700d5c10-8c27-4a6c-8a51-0b088a5934ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='u_4_l_U6']/span/select</value>
      <webElementGuid>c07da8a4-3663-42c1-9c9a-b368891c3deb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
